Repository ZenBit-Tech/sunny-bunnies_fe, pull requests merged in 2024-07, with the labels that each got.

#44 Fix imports
  src/pages/product/components/product-description/index.tsx
  src/pages/product/components/sizes-dropdown/index.tsx
  src/pages/product/components/vendor-preview-mode-modal/index.tsx
  src/pages/product/index.tsx
Labels: bug

#46 Feature sb 131 test set up
  README.md
  package-lock.json
  package.json
  src/pages/profile/components/address-modal/use-address-form.test.ts
  src/test/providers.tsx
  src/test/test-utils.tsx
  tsconfig.json
  vite.config.ts
  vitest.setup.ts
Labels: documentation, enhancement

#45 Feature sb 120 add pagination
  src/components/index.ts
  src/components/pagination/index.tsx
  src/components/pagination/styles.ts
  src/index.tsx
  src/libs/constants/index.ts
  src/libs/constants/pagination.ts
  src/libs/hooks/index.ts
  src/libs/hooks/use-pagination.hook.ts
  src/libs/types/user.ts
  src/mui.d.ts
  src/pages/admin-panel/component/user-management/index.tsx
  src/pages/admin-panel/component/user-management/styles.ts
  src/pages/terms-conditions/index.tsx
  src/redux/admin/admin-api.ts
  src/theme.ts
Labels: enhancement

#48 Feature: sb 131 test setup
  .gitignore
  README.md
  package-lock.json
  package.json
  src/redux/filters/filters-api.test.ts
  src/test/handlers.ts
  src/test/mock-server.ts
  src/test/mocks/all-filters.ts
  src/test/mocks/index.ts
  vite.config.ts
  vitest.setup.ts
Labels: documentation, enhancement

#49 fix: fix modal and image in form
  src/pages/profile/components/address-modal/index.tsx
  src/pages/profile/components/address-modal/use-address-modal.test.ts
  src/pages/profile/components/address-modal/use-address-modal.ts
  src/pages/profile/components/profile-form/use-profile-form.ts
  src/pages/profile/components/profile-menu/index.tsx
  src/pages/profile/components/profile-menu/styles.ts
Labels: bug

#50 fix: closing modal after submission
  src/pages/profile/components/address-modal/use-address-modal.ts
Labels: bug

#33 Feature sb 44 password restore
  bun.lockb
  src/assets/images/auth/index.ts
  src/assets/images/auth/reset-password-image.png
  src/assets/images/auth/restore-password-image.png
  src/components/base-button/base-button.test.tsx
  src/components/base-button/index.tsx
  src/components/custom-form-group/index.tsx
  src/index.tsx
  src/libs/constants/app-route.ts
  src/libs/locales/translation.json
  src/libs/types/user.ts
  src/pages/auth/components/admin-login/index.tsx
  src/pages/auth/components/auth-links/index.tsx
  src/pages/auth/components/forgot-password-link/index.tsx
  src/pages/auth/components/forgot-password-link/restore-password-schema.ts
  src/pages/auth/components/index.ts
  src/pages/auth/components/reset-password-form/index.tsx
  src/pages/auth/components/reset-password-form/reset-password-form.test.tsx
  src/pages/auth/components/reset-password-form/reset-password-schema.ts
  src/pages/auth/components/reset-password-form/use-reset-password-form.hook.ts
  src/pages/auth/components/restore-password-form/index.tsx
  src/pages/auth/components/restore-password-form/use-restore-password-form.hook.ts
  src/pages/auth/components/restore-password-form/use-restore-password-form.test.tsx
  src/pages/auth/components/sign-in-form/index.tsx
  src/pages/auth/components/sign-in-form/use-sign-in-form.ts
  src/pages/auth/components/sign-in-link/index.tsx
  src/pages/auth/components/sign-up-form/index.tsx
  src/pages/auth/components/sign-up-form/sign-up-schema.ts
  src/pages/auth/components/sign-up-form/use-sign-up-form.ts
  src/pages/auth/components/sign-up-link/index.tsx
  src/pages/auth/components/verify-email-form/index.tsx
  src/pages/auth/components/verify-email-form/use-verify-otp-form.ts
  src/pages/auth/hooks/index.ts
  src/pages/auth/index.tsx
  src/pages/auth/validation/index.ts
  src/redux/auth/auth-api.test.ts
  src/redux/auth/auth-api.ts
  src/redux/auth/constants.ts
  src/test/handlers.ts
  src/test/providers.tsx
Labels: enhancement

#51 fix: size shoes and jeans
  src/pages/profile-board/components/size-form.tsx
Labels: bug

#53 Fix sb 169 incorrect sorting UI and update status behavior
  src/pages/admin-panel/component/user-management/index.tsx
  src/pages/admin-panel/component/user-table/index.tsx
  src/pages/admin-panel/component/user-table/styles.ts
  src/pages/admin-panel/component/user-table/user-table.test.tsx
  src/pages/admin-panel/constants/index.ts
  src/pages/admin-panel/constants/sort-order.ts
Labels: bug

#56 Feature sb 175 new header
  src/assets/icons/arrow-left-icon.tsx
  src/assets/icons/box-icon.tsx
  src/assets/icons/letter-icon.tsx
  src/assets/icons/notification-icon.tsx
  src/assets/icons/shop-cart-icon.tsx
  src/assets/icons/twitter-icon.tsx
  src/assets/icons/user-icon.tsx
  src/components/Footer/styles.ts
  src/components/Header/Button.tsx
  src/components/Header/Header.tsx
  src/components/Header/main-logo.tsx
  src/components/Header/nav-header.tsx
  src/components/Header/styles.ts
  src/components/circular/index.tsx
  src/components/footer/index.tsx
  src/components/footer/nav-footer/index.tsx
  src/components/footer/social-icons/index.tsx
  src/components/footer/social-icons/social-icon.tsx
  src/components/footer/styles.ts
  src/components/footer/wrapper/index.tsx
  src/components/header/auth-user-content/index.tsx
  src/components/header/guest-user-content/index.tsx
  src/components/header/guest-user-content/styles.ts
  src/components/header/index.tsx
  src/components/header/main-logo/index.tsx
  src/components/header/nav-header/index.tsx
  src/components/header/nav-header/styles.ts
  src/components/header/styles.ts
  src/components/header/wrapper/index.tsx
  src/components/index.ts
  src/components/link/index.tsx
  src/components/private-route/index.tsx
  src/libs/constants/header-links.ts
  src/libs/constants/index.ts
  src/libs/constants/register-route.ts
  src/pages/home/index.tsx
Labels: enhancement

#60 Feature sb-178 add notifications
  package-lock.json
  package.json
  src/components/index.ts
  src/components/notification/index.tsx
  src/components/notification/notification.test.tsx
  src/index.tsx
  src/libs/locales/translation.json
  src/libs/notification/enums/index.ts
  src/libs/notification/enums/notification-message.enum.ts
  src/libs/notification/enums/notification-type.enum.ts
  src/libs/notification/index.ts
  src/libs/notification/notification.module.ts
  src/libs/types/value-of.type.ts
  src/pages/admin-panel/component/user-profile/user-profile-hook.ts
  src/pages/auth/components/reset-password-form/use-reset-password-form.hook.ts
  src/pages/auth/components/restore-password-form/use-restore-password-form.hook.ts
  src/pages/auth/components/verify-email-form/index.tsx
  src/pages/profile/components/profile-form/use-profile-form.ts
Labels: enhancement

#57 Feature sb 100 products requests
  src/assets/icons/confirm-icon.tsx
  src/assets/icons/decline-icon.tsx
  src/index.tsx
  src/libs/constants/app-route.ts
  src/libs/constants/colors.ts
  src/libs/locales/translation.json
  src/libs/types/products.ts
  src/mui.d.ts
  src/pages/admin-panel/component/index.ts
  src/pages/admin-panel/component/product-management/index.tsx
  src/pages/admin-panel/component/product-management/styles.ts
  src/pages/admin-panel/component/product-status/index.tsx
  src/pages/admin-panel/component/product-status/styles.ts
  src/pages/admin-panel/component/products-table/index.tsx
  src/pages/admin-panel/component/products-table/styles.ts
  src/pages/admin-panel/component/sidebar/sidebar-list/index.tsx
  src/pages/admin-panel/index.tsx
  src/pages/home/hooks/use-product-search.ts
  src/pages/home/hooks/use-products-filters.ts
  src/pages/home/index.tsx
  src/redux/admin/admin-api.test.ts
  src/redux/admin/admin-api.ts
  src/redux/admin/constants.ts
  src/redux/products/products-api.ts
  src/test/handlers.ts
  src/test/mocks/index.ts
  src/test/mocks/products.ts
  src/theme.ts
Labels: enhancement

#59 fix: avatar styles in profile form
  src/pages/profile/components/profile-form/index.tsx
Labels: bug

#39 Feature sb 66 vendor public page
  src/assets/icons/like-icon.tsx
  src/helpers/index.ts
  src/helpers/sort-sizes-by-asc-order.ts
  src/libs/constants/colors.ts
  src/mui.d.ts
  src/pages/product/index.tsx
  src/pages/profile/components/profile-form/constants.ts
  src/pages/profile/components/profile-form/profile-schema.ts
  src/pages/vendor-profile/components/like-icon/index.tsx
  src/pages/vendor-profile/components/product-card/index.tsx
  src/pages/vendor-profile/components/product-card/styles.ts
  src/pages/vendor-profile/components/products-section/styles.ts
  src/pages/vendor-profile/components/review-item/index.tsx
  src/pages/vendor-profile/components/vendor-avatar-section/index.tsx
  src/pages/vendor-profile/components/vendor-avatar-section/styles.ts
  src/pages/vendor-profile/components/vendors-products-and-reviews/styles.ts
  src/pages/vendor-profile/index.tsx
  src/pages/vendor-profile/styles.ts
  src/theme.ts
Labels: enhancement

#62 fix: hotfix
  src/pages/product/components/recommended-products/index.tsx
Labels: bug

#58 Feature sb-103 refactor sidebar
  src/assets/icons/dashbord-icon.tsx
  src/assets/icons/heart-icon.tsx
  src/components/footer/wrapper/index.tsx
  src/components/header/wrapper/index.tsx
  src/components/notification/notification.test.tsx
  src/components/profile-menu/get-buttons.tsx
  src/components/profile-menu/index.tsx
  src/index.tsx
  src/libs/constants/app-route.ts
  src/libs/locales/translation.json
  src/pages/profile/index.tsx
Labels: enhancement

#63 Feature sb-67 new product card
  package-lock.json
  package.json
  src/assets/icons/filled-heart-icon.tsx
  src/assets/icons/shop-cart-icon.tsx
  src/components/product-card/constats.ts
  src/components/product-card/index.tsx
  src/components/product-card/product-slider/index.tsx
  src/components/product-card/styles.ts
  src/pages/home/components/products/index.tsx
  src/pages/home/components/products/styles.ts
  src/pages/product/styles.ts
Labels: enhancement

#64 feat: admin product list
  src/components/animated-button/index.tsx
  src/components/animated-button/styles.ts
  src/components/delete-modal/index.tsx
  src/components/delete-modal/styles.ts
  src/components/index.ts
  src/index.tsx
  src/libs/locales/translation.json
  src/pages/admin-panel/component/product-management/index.tsx
  src/pages/admin-panel/component/products-table/index.tsx
  src/pages/admin-panel/component/sidebar/sidebar-list/index.tsx
  src/pages/admin-panel/component/user-profile/index.tsx
  src/pages/admin-panel/index.tsx
  src/redux/admin/admin-api.test.ts
  src/redux/admin/admin-api.ts
  src/redux/admin/constants.ts
  src/test/handlers.ts
Labels: enhancement
