Repository ZenBit-Tech/sunny-bunnies_fe, pull requests merged in 2024-06, with the labels that each got.

#5 Feature sb 27 tc and pp
  src/components/common/wrappers/footer-wrapper.tsx
  src/components/common/wrappers/header-wrapper.tsx
  src/index.tsx
  src/libs/constants/footer-links.ts
  src/libs/constants/random.ts
  src/libs/locales/translation.json
  src/pages/privacy-policy/privacy-policy-articles.ts
  src/pages/privacy-policy/privacy-policy-page.tsx
  src/pages/privacy-policy/styles.ts
  src/pages/terms-conditions/terms-and-conditions.tsx
  src/pages/terms-conditions/terms-conditions-articles.ts
Labels: enhancement

#6 Fix sb 24 sign up with google
  src/assets/images/auth/Google.png
  src/assets/images/auth/index.ts
  src/pages/auth/index.tsx
Labels: bug

#7 Feature sb 15 sign in with google
  eslint.config.js
  src/pages/auth/components/sign-in-form.tsx
  src/pages/auth/components/sign-up-form.tsx
  src/pages/auth/hooks/use-sign-in-form.ts
  src/pages/auth/index.tsx
  src/redux/auth/auth-api.ts
  src/redux/auth/constants.ts
Labels: enhancement

#9 fix: change path for current user
  src/redux/auth/auth-api.ts
  src/redux/auth/constants.ts
Labels: good first issue

#11 feat: add not found page
  src/index.tsx
  src/libs/locales/translation.json
  src/pages/index.ts
  src/pages/not-found/index.tsx
  src/pages/not-found/styles.ts
Labels: enhancement

#10 fix: changed styles on auth page
  src/assets/images/logo/big.png
  src/components/custom-form-group/index.tsx
  src/pages/auth/components/sign-up-form.tsx
  src/pages/auth/components/styles.ts
  src/pages/auth/index.tsx
Labels: bug

#12 Fix sb 89 fix paddings on sign up page
  src/pages/auth/components/auth-links.tsx
Labels: bug

#13 Fix sb 90 incorrect error message
  src/pages/auth/validation/constants.ts
  src/pages/auth/validation/sign-up-schema.ts
Labels: bug

#14 Fix sb 94 add links on header
  src/components/Header/Header.tsx
  src/libs/constants/index.ts
Labels: bug

#15 Feature sb 34 size guide page
  src/components/common/wrappers/footer-wrapper.tsx
  src/components/common/wrappers/header-wrapper.tsx
  src/index.tsx
  src/libs/constants/app-route.ts
  src/libs/constants/colors.ts
  src/libs/constants/fonts.ts
  src/libs/constants/index.ts
  src/libs/constants/sizes.ts
  src/libs/locales/translation.json
  src/pages/auth/index.tsx
  src/pages/index.ts
  src/pages/size-guide/components/index.ts
  src/pages/size-guide/components/table-with-title/index.tsx
  src/pages/size-guide/components/table-with-title/styles.ts
  src/pages/size-guide/index.tsx
  src/pages/size-guide/styles.ts
Labels: enhancement

#16 Feat deploy
  .env.example
  package.json
  tsconfig.json
  vite.config.ts
Labels: enhancement

#18 Featutre sb 61 otp email verifying
  images.d.ts
  package-lock.json
  package.json
  src/assets/icons/arrow-left-icon.tsx
  src/assets/images/auth/index.ts
  src/assets/images/auth/verify-email.png
  src/components/common/wrappers/header-wrapper.tsx
  src/components/private-route/index.tsx
  src/components/public-route/index.tsx
  src/index.tsx
  src/libs/hooks/index.ts
  src/libs/hooks/use-timer.ts
  src/libs/types/user.ts
  src/pages/auth/components/styles.ts
  src/pages/auth/components/verify-email-form.tsx
  src/pages/auth/hooks/use-verify-otp-form.ts
  src/pages/auth/index.tsx
  src/redux/auth/auth-api.ts
  src/redux/auth/constants.ts
Labels: enhancement

#17 Feature: sb 84 products filters
  package-lock.json
  package.json
  src/components/custom-radio-button-group/index.tsx
  src/components/custom-radio-button-group/styles.ts
  src/components/custom-radio-buttons/index.tsx
  src/components/custom-select/index.tsx
  src/components/custom-slider/index.tsx
  src/components/index.ts
  src/helpers/index.ts
  src/helpers/is-color-light.ts
  src/libs/locales/translation.json
  src/libs/types/filters.ts
  src/pages/home/components/color-picker/index.tsx
  src/pages/home/components/color-picker/styles.ts
  src/pages/home/components/filter-tags/index.tsx
  src/pages/home/components/index.ts
  src/pages/home/components/product-filters/index.tsx
  src/pages/home/components/product-filters/styles.ts
  src/pages/home/components/product-search/index.tsx
  src/pages/home/components/products/index.tsx
  src/pages/home/hooks/index.ts
  src/pages/home/hooks/use-product-search.ts
  src/pages/home/hooks/use-products-filters.ts
  src/pages/home/index.tsx
  src/redux/filters/constants.ts
  src/redux/filters/filters-api.ts
  src/redux/filters/filters.slice.ts
  src/redux/products/products-api.ts
  src/redux/products/products-slice.ts
  src/redux/store.ts
Labels: enhancement

#21 Feature sb 74 public product page
  package-lock.json
  package.json
  src/assets/images/product/bag-check.svg
  src/assets/images/product/chat-dots.svg
  src/assets/images/product/index.ts
  src/assets/images/product/wish-list-heart.svg
  src/components/common/wrappers/footer-wrapper.tsx
  src/components/common/wrappers/header-wrapper.tsx
  src/index.tsx
  src/libs/constants/app-route.ts
  src/libs/constants/fonts.ts
  src/libs/constants/product-status.ts
  src/libs/locales/translation.json
  src/libs/types/products.ts
  src/libs/types/user.ts
  src/mui.d.ts
  src/pages/home/components/product-card/index.tsx
  src/pages/home/index.tsx
  src/pages/index.ts
  src/pages/product/components/header-links-group/index.tsx
  src/pages/product/components/header-links-group/styles.ts
  src/pages/product/components/images-slider/images-slider-element.tsx
  src/pages/product/components/images-slider/index.tsx
  src/pages/product/components/images-slider/styles.ts
  src/pages/product/components/index.ts
  src/pages/product/components/product-buttons-group/index.tsx
  src/pages/product/components/product-buttons-group/styles.ts
  src/pages/product/components/product-description/description-details-item.tsx
  src/pages/product/components/product-description/index.tsx
  src/pages/product/components/product-description/styles.ts
  src/pages/product/components/product-header/index.tsx
  src/pages/product/components/product-header/styles.ts
  src/pages/product/components/product-status-radio/index.tsx
  src/pages/product/components/product-status-radio/styles.ts
  src/pages/product/components/radio-label/index.tsx
  src/pages/product/components/radio-label/styles.ts
  src/pages/product/components/recommended-products/index.tsx
  src/pages/product/components/recommended-products/styles.ts
  src/pages/product/components/sizes-dropdown/index.tsx
  src/pages/product/components/vendor-preview-header/index.tsx
  src/pages/product/components/vendor-preview-header/styles.ts
  src/pages/product/components/vendor-preview-mode-modal/index.tsx
  src/pages/product/components/vendor-preview-mode-modal/styles.ts
  src/pages/product/index.tsx
  src/pages/product/styles.ts
  src/pages/size-guide/components/table-with-title/index.tsx
  src/redux/products/products-api.ts
  src/theme.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: documentation, enhancement

#22 feat: add upload avatar sb-49
  src/components/image-preview/image-preview.tsx
  src/libs/locales/translation.json
  src/libs/types/user-profile.type.ts
  src/pages/profile-board/components/general-information-form.tsx
  src/pages/profile-board/validation/constants.ts
  src/pages/profile-board/validation/credit-card-schema.ts
  src/pages/profile-board/validation/general-information-validation.ts
  src/redux/user/constants.ts
  src/redux/user/user-api.ts
Labels: documentation, enhancement

#23 Feature sb 82 admin login
  src/index.tsx
  src/libs/constants/app-route.ts
  src/libs/locales/translation.json
  src/pages/auth/components/admin-login.tsx
  src/pages/auth/components/index.ts
  src/pages/profile-board/index.tsx
  src/redux/auth/auth-api.ts
  src/redux/auth/constants.ts
  src/theme.ts
Labels: documentation, enhancement

#24 Feature sb 66 vendor page
  package-lock.json
  package.json
  src/assets/icons/shop-cart.svg
  src/assets/icons/star-rating-icon.svg
  src/components/common/wrappers/footer-wrapper.tsx
  src/components/common/wrappers/header-wrapper.tsx
  src/index.tsx
  src/libs/constants/app-route.ts
  src/libs/constants/colors.ts
  src/libs/locales/translation.json
  src/libs/types/vendor.ts
  src/mui.d.ts
  src/pages/home/components/product-card/index.tsx
  src/pages/index.ts
  src/pages/product/components/product-description/description-details-item.tsx
  src/pages/product/components/product-description/index.tsx
  src/pages/product/components/product-description/styles.ts
  src/pages/product/components/product-status-radio/index.tsx
  src/pages/product/components/product-status-radio/styles.ts
  src/pages/product/components/sizes-dropdown/index.tsx
  src/pages/product/index.tsx
  src/pages/vendor-profile/components/header-link-group/index.tsx
  src/pages/vendor-profile/components/header-link-group/styles.ts
  src/pages/vendor-profile/components/index.ts
  src/pages/vendor-profile/components/product-card/index.tsx
  src/pages/vendor-profile/components/product-card/styles.ts
  src/pages/vendor-profile/components/products-section/index.tsx
  src/pages/vendor-profile/components/products-section/styles.ts
  src/pages/vendor-profile/components/review-item/index.tsx
  src/pages/vendor-profile/components/review-item/styles.ts
  src/pages/vendor-profile/components/reviews-section/index.tsx
  src/pages/vendor-profile/components/reviews-section/styles.ts
  src/pages/vendor-profile/components/vendor-avatar-section/index.tsx
  src/pages/vendor-profile/components/vendor-avatar-section/styles.ts
  src/pages/vendor-profile/components/vendor-buttons-group/index.tsx
  src/pages/vendor-profile/components/vendor-buttons-group/styles.ts
  src/pages/vendor-profile/components/vendors-products-and-reviews/index.tsx
  src/pages/vendor-profile/components/vendors-products-and-reviews/styles.ts
  src/pages/vendor-profile/hooks/index.ts
  src/pages/vendor-profile/hooks/use-follow-handler.ts
  src/pages/vendor-profile/index.tsx
  src/pages/vendor-profile/styles.ts
  src/redux/user/constants.ts
  src/redux/user/user-api.ts
  src/theme.ts
Labels: documentation, enhancement

#25 Fix sb-118 fix incorerect behavior of google login
  src/pages/auth/components/sign-in-form.tsx
  src/redux/auth/auth-api.ts
Labels: bug

#28 Fix sb 123 incorrect behavior during verify otp
  src/pages/auth/hooks/use-verify-otp-form.ts
Labels: bug

#26 Fix private route
  src/components/private-route/index.tsx
  src/index.tsx
  src/libs/constants/index.ts
  src/libs/constants/user-role.ts
  src/pages/product/components/product-description/styles.ts
  src/pages/product/components/product-header/index.tsx
  src/pages/product/index.tsx
  src/pages/profile-board/index.tsx
  src/pages/vendor-profile/index.tsx
Labels: bug

#29 fix: added outlet in private route
  src/components/private-route/index.tsx
Labels: bug

#32 Fix sb 45 size for step 5 on profile board
  src/pages/profile-board/constants.ts/size.ts
Labels: bug

#36 Fix sb 45 size form
  src/pages/profile-board/components/size-form.tsx
Labels: bug

#35 Fix search no options text
  src/libs/locales/translation.json
  src/pages/home/components/product-search/index.tsx
  src/pages/home/hooks/use-product-search.ts
Labels: bug

#34 Fix:search input styles
  src/pages/home/components/product-search/index.tsx
  src/pages/home/components/products/index.tsx
Labels: bug

#41 Feature sb 101 admin menu
  src/assets/icons/arrow-down-icon.tsx
  src/assets/icons/chat-icon.tsx
  src/assets/icons/product-icon.tsx
  src/assets/icons/users-icon.tsx
  src/components/admin-route/admin-route.tsx
  src/components/auth-route/index.tsx
  src/components/index.ts
  src/index.tsx
  src/libs/constants/app-route.ts
  src/libs/constants/user-role.ts
  src/libs/locales/translation.json
  src/pages/admin-panel/admin-panel.tsx
  src/pages/admin-panel/component/index.ts
  src/pages/admin-panel/component/sidebar-list.tsx
  src/pages/admin-panel/component/sidebar.tsx
  src/pages/admin-panel/component/style.ts
  src/pages/admin-panel/component/user-management.tsx
  src/pages/admin-panel/hooks/use-is-route-active.ts
  src/pages/admin-panel/styles.ts
  src/pages/auth/components/admin-login.tsx
  src/pages/vendor-profile/index.tsx
  src/styles.css
  src/theme.ts
Labels: enhancement

#42 Fix sb 127 product card UI
  src/libs/constants/colors.ts
  src/pages/home/components/product-card/index.tsx
  src/pages/home/components/product-card/styles.ts
  src/pages/home/components/products/styles.ts
Labels: bug

#38 Feature sb 74 product preview page
  src/assets/icons/vendor-preview-icon.svg
  src/helpers/index.ts
  src/helpers/sort-sizes.ts
  src/libs/constants/colors.ts
  src/libs/constants/fonts.ts
  src/libs/constants/index.ts
  src/libs/constants/product-sizes-sort-order.ts
  src/libs/locales/translation.json
  src/pages/product/components/images-slider/index.tsx
  src/pages/product/components/product-buttons-group/index.tsx
  src/pages/product/components/product-buttons-group/styles.ts
  src/pages/product/components/product-description/index.tsx
  src/pages/product/components/product-description/styles.ts
  src/pages/product/components/product-header/index.tsx
  src/pages/product/components/product-header/styles.ts
  src/pages/product/components/product-status-radio/index.tsx
  src/pages/product/components/sizes-dropdown/index.tsx
  src/pages/product/components/sizes-dropdown/styles.ts
  src/pages/product/components/vendor-preview-mode-modal/index.tsx
  src/pages/product/components/vendor-preview-mode-modal/styles.ts
  src/pages/product/index.tsx
  src/pages/product/styles.ts
  src/pages/vendor-profile/index.tsx
  src/theme.ts
Labels: enhancement
